version: '3'

services:

 # ---------------------------------
 # laravelを動かすコンテナ
 # ---------------------------------
 app:
   ports:
     - "80:80"
   build: ./docker/app
   container_name: game-laravel
   volumes:
     - ./:/var/www/html

# ----------------------------------
# MySQLを動かすコンテナ
# ----------------------------------
 db:
   image: mysql:8.0
   container_name: game-mysql

   environment:
     MYSQL_ROOT_PASSWORD: root
     MYSQL_DATABASE: laravel_db
     MYSQL_USER: laravel_user
     MYSQL_PASSWORD: laravel_pass
     TZ: 'Asia/Tokyo'

   command: mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci
   volumes:
     - ./docker/db/data:/var/lib/mysql
     - ./docker/db/my.cnf:/etc/mysql/conf.d/my.cnf
   ports:
     - 3306:3306